server.port: 9000
logging.level.root: DEBUG
app:
  clients:
    hostname: elasticsearch
    scheme: http
    httpPort: 9200
  index:
    name: greeting
    type: _doc
    shard: 2
    replica: 1
    from: 0
    size: 5
    timeout: 60
spring:
  profiles:
    active: production
